#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ..

#filename of outputed .elf and .bin files
PROJECT = monta_test

#the folder the current app is in
APP_FOLDER = montatest

include $(BASE_PATH)/makefile
